## References made to ChatGPT: [link](https://chatgpt.com/share/ddc7b1f8-4631-4437-a54e-5c52f4eb8f26)

In [ ]:
## 00 pytorch fundamentals

In [ ]:
print("Hello I am excited to learn pytorch!")

Hello I am excited to learn pytorch!


In [ ]:
!nvidia-smi

Fri Oct  4 11:02:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
print(torch.__version__)

## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scaler = torch.tensor(7)

print(scaler.shape)
scaler

torch.Size([])


tensor(7)

In [ ]:
scaler.ndim, scaler.item()

(0, 7)

In [ ]:
# vector
vector = torch.tensor([1, 2, 3])
vector


tensor([1, 2, 3])

In [ ]:
vector.shape, vector.ndim, vector[2]

(torch.Size([3]), 1, tensor(3))

In [ ]:
# MATRIX
MATRIX = torch.tensor([[3, 4], [5, 6]])
MATRIX

tensor([[3, 4],
        [5, 6]])

In [ ]:
MATRIX.ndim, MATRIX[1]

(2, tensor([5, 6]))

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 6, 7]], [[1, 2, 3], [4, 6, 7]], [[1, 2, 3], [4, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 6, 7]],

        [[1, 2, 3],
         [4, 6, 7]],

        [[1, 2, 3],
         [4, 6, 7]]])

In [ ]:
TENSOR.size(), TENSOR.shape

(torch.Size([3, 2, 3]), torch.Size([3, 2, 3]))

In [ ]:
TENSOR[2][1][0]

tensor(4)

## Random Numbers

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust these radom numbers to better represent data.

`Start with random numbers -> look at data -> update the random numebrs -> look at data -> update the random numbers`

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4) # or (size=(3, 4))
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, RGB
random_image_size_tensor

tensor([[[0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860],
         ...,
         [0.1579, 0.2243, 0.8650],
         [0.6578, 0.6615, 0.2881],
         [0.4931, 0.9576, 0.1999]],

        [[0.5039, 0.7378, 0.1548],
         [0.9856, 0.2502, 0.3799],
         [0.3647, 0.1742, 0.0094],
         ...,
         [0.3149, 0.4460, 0.7700],
         [0.1527, 0.1840, 0.3880],
         [0.3186, 0.6964, 0.8365]],

        [[0.4465, 0.9728, 0.2911],
         [0.2194, 0.2762, 0.1555],
         [0.1495, 0.0545, 0.0569],
         ...,
         [0.6197, 0.4380, 0.9035],
         [0.1090, 0.7437, 0.1813],
         [0.0620, 0.3974, 0.7437]],

        ...,

        [[0.2719, 0.6953, 0.1937],
         [0.4471, 0.9488, 0.6033],
         [0.7192, 0.7423, 0.2911],
         ...,
         [0.7390, 0.2053, 0.3377],
         [0.4264, 0.9190, 0.7629],
         [0.4974, 0.7341, 0.7967]],

        [[0.6198, 0.7465, 0.0777],
         [0.7103, 0.5109, 0.0736],
         [0.

## Zeros and Ones

In [ ]:
# Create tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones * random_tensor)
ones, ones.dtype #dtype -> default data type(float32)


tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1,  end=11, step=1) # or torch.arange(1, 10, 2)
one_to_ten


In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_ones = torch.ones_like(one_to_ten)
ten_zeros, ten_ones

## Tensor Datatypes

**Note:** Tensor datatype  is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype -> `string * integer`
2. Tensors not right shape -> `in case of matrix multiplication, the dimenion is to be taken care of`
3. Tensors not on the right device -> `one tensor is on cpu and the other is on gpu and we need to work on both of those tensors at the same time`

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # what datatype is the tensor of(integer, float, etc.)
                                device=None, # what device the tensor is on(cpu or cude(gpu))
                                requires_grad=False) # whether to store the mathematical operations performed on the tensor to eventually find the gradient
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

## Getting information from the tensor

1. Tensor not right datatype -> use `tensor.dtype`
2. Tensor not right shape -> use `tensor.shape` or `tensor.size()`
1. Tensor not on the right device -> use `tensor.device`

In [ ]:
# Getting information
random_tensor = torch.rand(3, 4)
random_tensor.dtype, random_tensor.shape, random_tensor.size(), random_tensor.device

(torch.float32, torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'))

## Tensor Operations
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10, torch.add(tensor, 10), tensor.shape

(tensor([11, 12, 13]), tensor([11, 12, 13]), torch.Size([3]))

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

## Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication -> `(a, b) * (a, b) => (a, b)`
2. Matrix Multiplication(dot product) -> `(c, d) * (d, e) => (c, e)`

**Note:** There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work.
* `(2, 3) @ (3, 2)`will work.
* `(3, 2) @ (2, 3)` will work.

2. The resulting matrix has the shape of the **outer dimensions:**
* `(2, 3) @ (3, 2)` -> `(2, 2)`

In [ ]:
# Element-wise Multiplication
print(tensor * tensor)

tensor([1, 4, 9])


In [ ]:
%%time
# Matrix Multiplication
torch.matmul(tensor, tensor)

CPU times: user 461 µs, sys: 0 ns, total: 461 µs
Wall time: 8.96 ms


tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 577 µs, sys: 0 ns, total: 577 µs
Wall time: 610 µs


tensor(14)

## One of the most common errors in deep learning: shape errors

To fix tensor shape error, we can manipulate the shape of one of the tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is  the same as torch.matmul(it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.int64)

In [ ]:
# Min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
# Max
x.max(), torch.max(x)

(tensor(90), tensor(90))

### **Note**😈: torch.mean() works only on tensors which are of **float/complex data type**

In [ ]:
# Mean
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [ ]:
# Sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

## Positional Min and Max with Tensor

In [ ]:
# Find the position in tensor that has the maximum value with argmin()
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

## Reshaping, View, Stacking, Squeezing, Unsqueezing, Permute

* **Reshaping:** Reshapes an input tensor to a defined shape
* **View:** Returns a view of input tensor of defined shape but keep the same memory as the original tensor
* **Stacking:** Combine multiple tensors on top of each other (vstack) or side by side(hstack)
* **Squeeze:** Removes all `1` dimensions from a tensor
* **Unsqueeze:** Adds a `1` dimension to a target tensor
* **Permute:** Returns a view of the input tensor with the dimensions permuted(swapped) in a certain way

In [ ]:
# Create a tensor
x = torch.arange(1., 11.)

# Adding an extra dimension
x_reshaped = x.reshape(5, 1, 2, 1) # the numbers passed in the reshape function must multiply to the original tensor length
x_reshaped

tensor([[[[ 1.],
          [ 2.]]],


        [[[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]]],


        [[[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]]]])

In [ ]:
# Change the view
z = x.view(2, 5)
z

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
# Changing z changes x as well because the view of a tensor shares the same memory as the original tensor does
z[0][1] = -2
z, x

(tensor([[ 1., -2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([ 1., -2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x], dim=1) # dim = 0(hstack), dim = 1(vstack)
x_stacked

tensor([[ 1.,  1.],
        [-2., -2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.],
        [10., 10.]])

In [ ]:
## torch.squeeze() -> removes all single dimensions from a target tensor
x_reshaped, x_reshaped.squeeze()

(tensor([[[[ 1.],
           [-2.]]],
 
 
         [[[ 3.],
           [ 4.]]],
 
 
         [[[ 5.],
           [ 6.]]],
 
 
         [[[ 7.],
           [ 8.]]],
 
 
         [[[ 9.],
           [10.]]]]),
 tensor([[ 1., -2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]))

In [ ]:
## torch.unsqueeze() -> adds a single dimension at a particular dim for a target tensor
x_reshaped.squeeze().unsqueeze(dim=1)

tensor([[[ 1., -2.]],

        [[ 3.,  4.]],

        [[ 5.,  6.]],

        [[ 7.,  8.]],

        [[ 9., 10.]]])

## ***Note:*** torch.permute shares the same memory with the original tensor. So, if you make nay changes in the cell item of permute,  the x_original will also change.

In [ ]:
# torch.permute() -> rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(244, 244, 3) # height, width, RBG

x_permuted = x_original.permute(2, 0, 1) # RBG, height, width
x_permuted.shape

torch.Size([3, 244, 244])

## Indexing(selecting data from tensors)

Indexing with PyTorch is ismilar to indexing with NumPy.

In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

You can also use **':'**to select **all**

In [ ]:
# get all the values of the 0th and 1st dimension but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all the values of the 0th dimension but only index 1 of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of the 0th and 1st dimension and all values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Convert data in NumPy to PyTorch tensor -> use `torch.from_numpy(ndarray)`
* Convert PyTorch tensor to NumPy -> use `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype # The tensor takes the default datatype of the numpy(float64) unless, stated otherwise.

(dtype('float64'), torch.float64)

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array and see if it changes the value of tensor
# If not, means they do not share the same memory.

array[2] = 100
array, tensor

(array([  2.,   3., 100.,   5.,   6.,   7.,   8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy
tensor = torch.zeros(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
tensor[2] = 100
tensor, numpy_tensor

(tensor([  0.,   0., 100.,   0.,   0.,   0.,   0.]),
 array([  0.,   0., 100.,   0.,   0.,   0.,   0.], dtype=float32))

In [ ]:
# Change the tensor, what happens to the numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([  1.,   1., 101.,   1.,   1.,   1.,   1.]),
 array([  0.,   0., 100.,   0.,   0.,   0.,   0.], dtype=float32))

## Reproducibility

In short how neural network learns:

`start with random numbers -> tensor operations -> update the random numbers to try and make them better represent the data -> again -> again ....`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed.**

Reproducibility in PyTorch ensures that the **results of your code are the same every time you run it**. This is important for debugging, testing, and comparing different models.

In [ ]:
# Create 2 random tensors
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)
tensor_A == tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(3, 4)

tensor_A == tensor_B

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on the GPUs(and making faster computations)

GPUs = Faster computation on numbers, using CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good and quick.

### 1. Getting a GPU

1. Use Google Colab for a free GPU (options to upgrade as well).
2. Use your own GPU - takes a little bit of more setup and requires the investment of purchasing a GPU.
3. Use Cloud Computing - GCP, AWS, Azure.. these services allow you t rent computers on the cloud and access them.  


In [ ]:
!nvidia-smi

Fri Oct  4 11:02:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 2. Check for GPU access with PyTorch


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnoistic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the  GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
 # Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move the tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to the CPU

**Note:** Numpy doesn't work with the GPU.



In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu